// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cvr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Branch
    {
        /// <summary>
        /// Initializes a new instance of the Branch class.
        /// </summary>
        public Branch()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Branch class.
        /// </summary>
        public Branch(string branchCode = default(string), string name = default(string))
        {
            BranchCode = branchCode;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branchCode")]
        public string BranchCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
