// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cvr.Client.Models
{
    using Newtonsoft.Json;

    public partial class Company
    {
        /// <summary>
        /// Initializes a new instance of the Company class.
        /// </summary>
        public Company()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Company class.
        /// </summary>
        /// <param name="id">The company object Id. This may differ between
        /// providers.</param>
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)
        public Company(string id = default(string), string cvrNumber = default(string), string companyName = default(string), string phoneNumber = default(string), string eMailAddress = default(string), string mainBusinessCode = default(string), string mainBusinessDescription = default(string), string businessTypeCode = default(string), string dataProvider = default(string), CvrAddress cvrAddress = default(CvrAddress))
#pragma warning restore CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)
        {
            Id = id;
            CvrNumber = cvrNumber;
            CompanyName = companyName;
            PhoneNumber = phoneNumber;
            EMailAddress = eMailAddress;
            MainBusinessCode = mainBusinessCode;
            MainBusinessDescription = mainBusinessDescription;
            BusinessTypeCode = businessTypeCode;
            DataProvider = dataProvider;
            CvrAddress = cvrAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the company object Id. This may differ between
        /// providers.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cvrNumber")]
        public string CvrNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eMailAddress")]
        public string EMailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainBusinessCode")]
        public string MainBusinessCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainBusinessDescription")]
        public string MainBusinessDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "businessTypeCode")]
        public string BusinessTypeCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataProvider")]
        public string DataProvider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cvrAddress")]
        public CvrAddress CvrAddress { get; set; }

    }
}
