// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cvr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CompanyEvent
    {
        /// <summary>
        /// Initializes a new instance of the CompanyEvent class.
        /// </summary>
        public CompanyEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CompanyEvent class.
        /// </summary>
        /// <param name="id">The CVR identifier</param>
        /// <param name="action">A description of the action that occurred.
        /// This may differ between providers.</param>
        /// <param name="actionDateTime">The date and time the action
        /// occurred</param>
        public CompanyEvent(string id = default(string), string action = default(string), System.DateTime? actionDateTime = default(System.DateTime?))
        {
            Id = id;
            Action = action;
            ActionDateTime = actionDateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the CVR identifier
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets a description of the action that occurred. This may
        /// differ between providers.
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// Gets the date and time the action occurred
        /// </summary>
        [JsonProperty(PropertyName = "actionDateTime")]
        public System.DateTime? ActionDateTime { get; private set; }

    }
}
