// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cvr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CvrAddress
    {
        /// <summary>
        /// Initializes a new instance of the CvrAddress class.
        /// </summary>
        public CvrAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CvrAddress class.
        /// </summary>
        public CvrAddress(string publicRegistryId = default(string), string streetCode = default(string), string streetName = default(string), string houseNumber = default(string), string floor = default(string), string room = default(string), string citySubDivision = default(string), string communityCode = default(string), string postCode = default(string), string postDistrict = default(string), string countryCode = default(string))
        {
            PublicRegistryId = publicRegistryId;
            StreetCode = streetCode;
            StreetName = streetName;
            HouseNumber = houseNumber;
            Floor = floor;
            Room = room;
            CitySubDivision = citySubDivision;
            CommunityCode = communityCode;
            PostCode = postCode;
            PostDistrict = postDistrict;
            CountryCode = countryCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publicRegistryId")]
        public string PublicRegistryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetCode")]
        public string StreetCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetName")]
        public string StreetName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "houseNumber")]
        public string HouseNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "floor")]
        public string Floor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "room")]
        public string Room { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "citySubDivision")]
        public string CitySubDivision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "communityCode")]
        public string CommunityCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postCode")]
        public string PostCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postDistrict")]
        public string PostDistrict { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryCode")]
        public string CountryCode { get; set; }

    }
}
