// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cvr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LineOfIndustries
    {
        /// <summary>
        /// Initializes a new instance of the LineOfIndustries class.
        /// </summary>
        public LineOfIndustries()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LineOfIndustries class.
        /// </summary>
        public LineOfIndustries(Branch mainBusiness = default(Branch), Branch biBranch1 = default(Branch), Branch biBranch2 = default(Branch), Branch biBranch3 = default(Branch))
        {
            MainBusiness = mainBusiness;
            BiBranch1 = biBranch1;
            BiBranch2 = biBranch2;
            BiBranch3 = biBranch3;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainBusiness")]
        public Branch MainBusiness { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "biBranch1")]
        public Branch BiBranch1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "biBranch2")]
        public Branch BiBranch2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "biBranch3")]
        public Branch BiBranch3 { get; set; }

    }
}
