// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cvr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductionUnitDetail
    {
        /// <summary>
        /// Initializes a new instance of the ProductionUnitDetail class.
        /// </summary>
        public ProductionUnitDetail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductionUnitDetail class.
        /// </summary>
        public ProductionUnitDetail(string pNumber = default(string), string cvrNumber = default(string), string productionUnitName = default(string), string phoneNumber = default(string), string emailAddress = default(string), LocationAddress locationAddress = default(LocationAddress), LineOfIndustries lineOfIndustries = default(LineOfIndustries))
        {
            PNumber = pNumber;
            CvrNumber = cvrNumber;
            ProductionUnitName = productionUnitName;
            PhoneNumber = phoneNumber;
            EmailAddress = emailAddress;
            LocationAddress = locationAddress;
            LineOfIndustries = lineOfIndustries;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pNumber")]
        public string PNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cvrNumber")]
        public string CvrNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productionUnitName")]
        public string ProductionUnitName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationAddress")]
        public LocationAddress LocationAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lineOfIndustries")]
        public LineOfIndustries LineOfIndustries { get; set; }

    }
}
